### PR TITLE
Fix placing multiple rockets on the same landing pad

### LINKED ISSUE #23799: Rocket dupe
### Your GTNH Discord Username

Kefir

### Your Pack Version

2.8.4-stable

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I tried to place 2 rockets on a **single** landing pad with them being in left and right hand.

### The Reality

It placed 2 rockets on one landing pad and when i broke it with either my sword or crossbow it duplicated and it dropped 2 rockets and one rocket was remaining on the landing pad.

Image

Image

### Your Proposal

I don't know how to fix this

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by sbancuz**
Partially fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23799

It seems to be an issue with the placement procedure and not with the backhand mod. When placing a rocket the pad doesn't actually gets filled and waited for a tickUpdate. So if someone places more than one rocket before the tick update it will put multiple.

I say partially since this pr only deals with the placement of the rockets, not the actual dupe. If someone manages to place more than one rocket on the same pad it will still lead to a dupe.

Also this can only cover rocket tiers from 1-3 + cargo

### CODE REVIEW

**Comment by sbancuz** [comment]
I can't continue this pr since I don't have access to galaxy space gtnh. If anyone has access and is interested feel free to pick it up!

File: src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityLandingPad.java [hunk 1]
```diff
@@ -74,6 +62,22 @@ public void updateEntity() {
...
+            final IDockable fuelable = (IDockable) e;
+
+            if (fuelable != this.dockedEntity && fuelable.isDockValid(this)) {
+                if (fuelable instanceof ILandable) {
+                    ((ILandable) fuelable).landEntity(this.xCoord, this.yCoord, this.zCoord);
+                } else {
+                    fuelable.setPad(this);
+                }
+            }
+            return true;
```
Comment (MalTeeez) [inline src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityLandingPad.java:78]: Shouldn't this return be at the end of the above if block?

**Review by MalTeeez — COMMENTED** [review]
@Dream-Master can u give this person access to galaxy space

File: src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityLandingPad.java (hunk 1 above)
Comment (sbancuz) [reply src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityLandingPad.java:78]: I don't think so, in all cases it just means that something is docked. It doesn't matter what. But looking again at this made me realize that maybe I should put a break in the loop that calls tryDockEntity

Comment (MalTeeez) [reply src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityLandingPad.java:78]: True, you don't react to the now docked thing aside from potentially fixing the faulty state on the pad, so it  looks good. Early exit also looks good!

**Comment by Dream-Master** [comment]
sure

**Comment by Dream-Master** [comment]
@sbancuz i add you as github dev

**Review by MalTeeez — APPROVED** [review]
