### PR TITLE
Fix the oxygen usage when entering water

### LINKED ISSUE #20451: GC oxygen tank drains when touching water
### Your GTNH Discord Username

Lily_Blanc

### Your Pack Version

2.8beta1

### Your Proposal

make it so when not actively drowning oxygen is not drained from oxygen tanks

### Your Goal

decided to test a change and discovered oxygen will still be drained even if not actually drowning or if having waterbreathing potion effect (https://github.com/GTNewHorizons/Galacticraft/pull/101)

### Your Vision

clean numbers <3

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [x] I understand this change request may be rejected due to other community members think it's inappropriate.
- [x] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by Yoshy2002**
currently, oxygen gets consumed as soon as the player touches water, not just when he actually submerges. Also, oxygen would be consumed if the player already had the water breathing effect active. This PR fixes both of these.
Tested in dev env and seemed to work perfectly fine.
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20451

### CODE REVIEW

File: src/main/java/micdoodle8/mods/galacticraft/core/util/OxygenUtil.java [hunk 1]
```diff
@@ -433,18 +433,45 @@ public static boolean inOxygenBubble(World worldObj, double avgX, double avgY, d
      * @param player The player to check and apply the effect to.
      */
     public static void applyWaterBreathingEffect(EntityPlayerMP player) {
```
Comment (Justxs) [inline src/main/java/micdoodle8/mods/galacticraft/core/util/OxygenUtil.java:435]: you could write it like this:

```
public static void applyWaterBreathingEffect(EntityPlayerMP player) {
    if (!isHeadInWater(player)) {
        return;
    }

    if (hasSufficientWaterBreathing(player)) {
        return;
    }

    if (!hasValidOxygenSetup(player)) {
        return;
    }

    GCPlayerStats stats = GCPlayerStats.get(player);
    ItemStack tank1 = stats.extendedInventory.getStackInSlot(2);
    ItemStack tank2 = stats.extendedInventory.getStackInSlot(3);

    if (!hasOxygen(tank1) && !hasOxygen(tank2)) {
        return;
    }

    // Apply effect
    player.addPotionEffect(new PotionEffect(Potion.waterBreathing.id, 220, 0, true));

    // Consume oxygen (prefer first tank)
    if (!consumeOxygen(tank1, player)) {
        consumeOxygen(tank2, player);
    }
}

private static boolean isHeadInWater(EntityPlayerMP player) {
    double eyeY = player.posY + player.getEyeHeight();
    int x = MathHelper.floor_double(player.posX);
    int y = MathHelper.floor_double(eyeY);
    int z = MathHelper.floor_double(player.posZ);

    return player.worldObj
            .getBlock(x, y, z)
            .getMaterial() == Material.water;
}

private static boolean hasSufficientWaterBreathing(EntityPlayerMP player) {
    if (!player.isPotionActive(Potion.waterBreathing)) {
        return false;
    }

    PotionEffect effect = player.getActivePotionEffect(Potion.waterBreathing);
    return effect != null && (effect.getDuration() > 220 || effect.getAmplifier() > 0);
}

private static boolean hasOxygen(ItemStack tank) {
    return tank != null
            && tank.getItem() instanceof ItemOxygenTank
            && tank.getMaxDamage() - tank.getItemDamage() > 0;
}

private static boolean consumeOxygen(ItemStack tank, EntityPlayerMP player) {
    if (!hasOxygen(tank)) {
        return false;
    }

    tank.damageItem(1, player);
    return true;
}
```
This will make the code more readable. My tip for you would be to always try to reduce nesting. Great video explaining and showing why: https://youtu.be/CFRhGnuXG-4?si=SBbLaRvHgAN8y1G8

Comment (Yoshy2002) [reply src/main/java/micdoodle8/mods/galacticraft/core/util/OxygenUtil.java:435]: refactored the code, thanks a lot for the tip (and code) :)

**Review by Justxs — APPROVED** [review]

**Review by sisyphussy — APPROVED** [review]
